sudo: required

language: generic
os:
  - linux

before_install:
  - wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - rm packages-microsoft-prod.deb
  - sudo apt-get update;
  - sudo apt-get install -y apt-transport-https
  - sudo apt-get update
  - sudo apt-get install -y dotnet-sdk-6.0

script:
  - "./build.sh"

after_success:
  - echo "Build Finished - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST)"
