CREATE TABLE dbo.Urls
(
	Id BIGINT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	Url VARCHAR(255) NOT NULL,
	Hash VARCHAR(50) NOT NULL,
	CreatedAt DATETIME2 NOT NULL
);

CREATE UNIQUE INDEX U_IDX_Hash ON dbo.Urls(Hash);
CREATE UNIQUE INDEX U_IDX_Url ON dbo.Urls(Url);
