--- 1 ---
CREATE TABLE dbo.Books
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
	Published DATETIME NOT NULL
);

CREATE TABLE dbo.Authors
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
);

CREATE TABLE dbo.BookCount
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	AuthorId INT NOT NULL,
	BookId INT NOT NULL,
	Quantity INT NOT NULL
);
