CREATE DATABASE PersonsDB;

CREATE TABLE PersonsDB.dbo.Persons
(
	Id BIGINT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	FirstName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100) NOT NULL,
	Age TINYINT NOT NULL,
	Gender CHAR NOT NULL CHECK (Gender = 'M' OR Gender = 'F')
);