CREATE TABLE dbo.Customers
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	FirstName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100) NOT NULL,
);

CREATE TABLE dbo.Salesmen
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	FirstName VARCHAR(100) NOT NULL,
	LastName VARCHAR(100) NOT NULL,
);

CREATE TABLE dbo.Orders
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	PurchaseAmount MONEY NOT NULL,
	OrderDatetime DATETIME NOT NULL,
	CustomerId INT NOT NULL,
	SalesmanId INT NOT NULL
);