CREATE TABLE dbo.LibraryUser
(
	Id INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	DateRegistered DATETIME NOT NULL,
)

CREATE TABLE dbo.BookAuthor
(
	Id INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	DateOfBirth DATETIME NOT NUll,
	DateOfDeath DATETIME
)

CREATE TABLE dbo.Book
(
	Id INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	AuthorId INT FOREIGN KEY REFERENCES BookAuthor(Id) NOT NULL,
	BookName VARCHAR(150) NOT NULL,
)

CREATE TABLE dbo.TakenHistory
(
	Id INT IDENTITY(1, 1) PRIMARY KEY NOT NULL,
	BookTaken INT FOREIGN KEY REFERENCES Book(Id) NOT NULL,
	TakenBy INT FOREIGN KEY REFERENCES LibraryUser(Id) NOT NULL,
	DateTaken DATETIME NOT NULL,
	DateReturned DATETIME
)