CREATE DATABASE HomeworkDB;

CREATE TABLE HomeworkDB.dbo.PhoneBook
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	UserFirstName VARCHAR(20) NOT NULL,
	UserLastName VARCHAR(20),
	MobileNumber VARCHAR(20) NOT NULL,
	OtherNumber VARCHAR(20)
)

CREATE TABLE HomeworkDB.dbo.LoginHistory
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	UserId INT NOT NULL,
	UserType VARCHAR(10) NOT NULL,
	LoginTime DATETIME NOT NULL,
	UserLocation VARCHAR(50) NOT NULL
)

CREATE TABLE HomeworkDB.dbo.BankAccount
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	CardId INT NOT NULL,
	CardType VARCHAR(10) NOT NULL,
	IsCredit CHAR NOT NULL,
	Balance MONEY NOT NULL
)

CREATE TABLE HomeworkDB.dbo.BankTransaction
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	SenderId INT NOT NULL,
	ReceiverId INT NOT NULL,
	OperationTime DATETIME NOT NULL,
	TransactionAmount MONEY NOT NULL
)

CREATE TABLE HomeworkDB.dbo.SchoolSchedule
(
	Id INT IDENTITY(1, 1) NOT NULL PRIMARY KEY,
	ClassId INT NOT NULL,
	MainTeacher VARCHAR(50) NOT NULL,
	PupilsQuantity TINYINT NOT NULL,
	ClassSummary VARCHAR(300)
)